//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FlowerAppModel", "FK_tbl_products_tbl_categories", "tbl_categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCFlowerApp.Models.tbl_categories), "tbl_products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCFlowerApp.Models.tbl_products), true)]
[assembly: EdmRelationshipAttribute("FlowerAppModel", "FK_tbl_creditCard_tbl_users", "tbl_users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCFlowerApp.Models.tbl_users), "tbl_creditCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCFlowerApp.Models.tbl_creditCard), true)]
[assembly: EdmRelationshipAttribute("FlowerAppModel", "FK_tbl_purchases_tbl_ticket", "tbl_ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCFlowerApp.Models.tbl_ticket), "tbl_purchases", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCFlowerApp.Models.tbl_purchases), true)]
[assembly: EdmRelationshipAttribute("FlowerAppModel", "FK_tbl_ticket_tbl_users", "tbl_users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCFlowerApp.Models.tbl_users), "tbl_ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCFlowerApp.Models.tbl_ticket), true)]

#endregion

namespace MVCFlowerApp.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FlowerAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FlowerAppEntities object using the connection string found in the 'FlowerAppEntities' section of the application configuration file.
        /// </summary>
        public FlowerAppEntities() : base("name=FlowerAppEntities", "FlowerAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlowerAppEntities object.
        /// </summary>
        public FlowerAppEntities(string connectionString) : base(connectionString, "FlowerAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlowerAppEntities object.
        /// </summary>
        public FlowerAppEntities(EntityConnection connection) : base(connection, "FlowerAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_categories> tbl_categories
        {
            get
            {
                if ((_tbl_categories == null))
                {
                    _tbl_categories = base.CreateObjectSet<tbl_categories>("tbl_categories");
                }
                return _tbl_categories;
            }
        }
        private ObjectSet<tbl_categories> _tbl_categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_creditCard> tbl_creditCard
        {
            get
            {
                if ((_tbl_creditCard == null))
                {
                    _tbl_creditCard = base.CreateObjectSet<tbl_creditCard>("tbl_creditCard");
                }
                return _tbl_creditCard;
            }
        }
        private ObjectSet<tbl_creditCard> _tbl_creditCard;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_products> tbl_products
        {
            get
            {
                if ((_tbl_products == null))
                {
                    _tbl_products = base.CreateObjectSet<tbl_products>("tbl_products");
                }
                return _tbl_products;
            }
        }
        private ObjectSet<tbl_products> _tbl_products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_purchases> tbl_purchases
        {
            get
            {
                if ((_tbl_purchases == null))
                {
                    _tbl_purchases = base.CreateObjectSet<tbl_purchases>("tbl_purchases");
                }
                return _tbl_purchases;
            }
        }
        private ObjectSet<tbl_purchases> _tbl_purchases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ticket> tbl_ticket
        {
            get
            {
                if ((_tbl_ticket == null))
                {
                    _tbl_ticket = base.CreateObjectSet<tbl_ticket>("tbl_ticket");
                }
                return _tbl_ticket;
            }
        }
        private ObjectSet<tbl_ticket> _tbl_ticket;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_users> tbl_users
        {
            get
            {
                if ((_tbl_users == null))
                {
                    _tbl_users = base.CreateObjectSet<tbl_users>("tbl_users");
                }
                return _tbl_users;
            }
        }
        private ObjectSet<tbl_users> _tbl_users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_usersRecords> tbl_usersRecords
        {
            get
            {
                if ((_tbl_usersRecords == null))
                {
                    _tbl_usersRecords = base.CreateObjectSet<tbl_usersRecords>("tbl_usersRecords");
                }
                return _tbl_usersRecords;
            }
        }
        private ObjectSet<tbl_usersRecords> _tbl_usersRecords;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_categories(tbl_categories tbl_categories)
        {
            base.AddObject("tbl_categories", tbl_categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_creditCard EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_creditCard(tbl_creditCard tbl_creditCard)
        {
            base.AddObject("tbl_creditCard", tbl_creditCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_products(tbl_products tbl_products)
        {
            base.AddObject("tbl_products", tbl_products);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_purchases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_purchases(tbl_purchases tbl_purchases)
        {
            base.AddObject("tbl_purchases", tbl_purchases);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ticket EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ticket(tbl_ticket tbl_ticket)
        {
            base.AddObject("tbl_ticket", tbl_ticket);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_users(tbl_users tbl_users)
        {
            base.AddObject("tbl_users", tbl_users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_usersRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_usersRecords(tbl_usersRecords tbl_usersRecords)
        {
            base.AddObject("tbl_usersRecords", tbl_usersRecords);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_categories object.
        /// </summary>
        /// <param name="iD_category">Initial value of the ID_category property.</param>
        /// <param name="category">Initial value of the category property.</param>
        public static tbl_categories Createtbl_categories(global::System.Int32 iD_category, global::System.String category)
        {
            tbl_categories tbl_categories = new tbl_categories();
            tbl_categories.ID_category = iD_category;
            tbl_categories.category = category;
            return tbl_categories;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_category
        {
            get
            {
                return _ID_category;
            }
            set
            {
                if (_ID_category != value)
                {
                    OnID_categoryChanging(value);
                    ReportPropertyChanging("ID_category");
                    _ID_category = StructuralObject.SetValidValue(value, "ID_category");
                    ReportPropertyChanged("ID_category");
                    OnID_categoryChanged();
                }
            }
        }
        private global::System.Int32 _ID_category;
        partial void OnID_categoryChanging(global::System.Int32 value);
        partial void OnID_categoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, false, "category");
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_products_tbl_categories", "tbl_products")]
        public EntityCollection<tbl_products> tbl_products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_products>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_products>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_products", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_creditCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_creditCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_creditCard object.
        /// </summary>
        /// <param name="id_creditcard">Initial value of the id_creditcard property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="digits">Initial value of the digits property.</param>
        /// <param name="month">Initial value of the month property.</param>
        /// <param name="year">Initial value of the year property.</param>
        /// <param name="card_address">Initial value of the card_address property.</param>
        /// <param name="iD_user">Initial value of the ID_user property.</param>
        public static tbl_creditCard Createtbl_creditCard(global::System.Int32 id_creditcard, global::System.String name, global::System.String digits, global::System.String month, global::System.String year, global::System.String card_address, global::System.Int32 iD_user)
        {
            tbl_creditCard tbl_creditCard = new tbl_creditCard();
            tbl_creditCard.id_creditcard = id_creditcard;
            tbl_creditCard.name = name;
            tbl_creditCard.digits = digits;
            tbl_creditCard.month = month;
            tbl_creditCard.year = year;
            tbl_creditCard.card_address = card_address;
            tbl_creditCard.ID_user = iD_user;
            return tbl_creditCard;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_creditcard
        {
            get
            {
                return _id_creditcard;
            }
            set
            {
                if (_id_creditcard != value)
                {
                    Onid_creditcardChanging(value);
                    ReportPropertyChanging("id_creditcard");
                    _id_creditcard = StructuralObject.SetValidValue(value, "id_creditcard");
                    ReportPropertyChanged("id_creditcard");
                    Onid_creditcardChanged();
                }
            }
        }
        private global::System.Int32 _id_creditcard;
        partial void Onid_creditcardChanging(global::System.Int32 value);
        partial void Onid_creditcardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String digits
        {
            get
            {
                return _digits;
            }
            set
            {
                OndigitsChanging(value);
                ReportPropertyChanging("digits");
                _digits = StructuralObject.SetValidValue(value, false, "digits");
                ReportPropertyChanged("digits");
                OndigitsChanged();
            }
        }
        private global::System.String _digits;
        partial void OndigitsChanging(global::System.String value);
        partial void OndigitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String month
        {
            get
            {
                return _month;
            }
            set
            {
                OnmonthChanging(value);
                ReportPropertyChanging("month");
                _month = StructuralObject.SetValidValue(value, false, "month");
                ReportPropertyChanged("month");
                OnmonthChanged();
            }
        }
        private global::System.String _month;
        partial void OnmonthChanging(global::System.String value);
        partial void OnmonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value, false, "year");
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private global::System.String _year;
        partial void OnyearChanging(global::System.String value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String card_address
        {
            get
            {
                return _card_address;
            }
            set
            {
                Oncard_addressChanging(value);
                ReportPropertyChanging("card_address");
                _card_address = StructuralObject.SetValidValue(value, false, "card_address");
                ReportPropertyChanged("card_address");
                Oncard_addressChanged();
            }
        }
        private global::System.String _card_address;
        partial void Oncard_addressChanging(global::System.String value);
        partial void Oncard_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_user
        {
            get
            {
                return _ID_user;
            }
            set
            {
                OnID_userChanging(value);
                ReportPropertyChanging("ID_user");
                _ID_user = StructuralObject.SetValidValue(value, "ID_user");
                ReportPropertyChanged("ID_user");
                OnID_userChanged();
            }
        }
        private global::System.Int32 _ID_user;
        partial void OnID_userChanging(global::System.Int32 value);
        partial void OnID_userChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_creditCard_tbl_users", "tbl_users")]
        public tbl_users tbl_users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_users> tbl_usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_products")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_products : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_products object.
        /// </summary>
        /// <param name="code_product">Initial value of the Code_product property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iD_Category">Initial value of the ID_Category property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static tbl_products Createtbl_products(global::System.String code_product, global::System.String name, global::System.Double price, global::System.String description, global::System.Int32 iD_Category, global::System.Int32 id)
        {
            tbl_products tbl_products = new tbl_products();
            tbl_products.Code_product = code_product;
            tbl_products.Name = name;
            tbl_products.Price = price;
            tbl_products.Description = description;
            tbl_products.ID_Category = iD_Category;
            tbl_products.ID = id;
            return tbl_products;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code_product
        {
            get
            {
                return _Code_product;
            }
            set
            {
                OnCode_productChanging(value);
                ReportPropertyChanging("Code_product");
                _Code_product = StructuralObject.SetValidValue(value, false, "Code_product");
                ReportPropertyChanged("Code_product");
                OnCode_productChanged();
            }
        }
        private global::System.String _Code_product;
        partial void OnCode_productChanging(global::System.String value);
        partial void OnCode_productChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Category
        {
            get
            {
                return _ID_Category;
            }
            set
            {
                OnID_CategoryChanging(value);
                ReportPropertyChanging("ID_Category");
                _ID_Category = StructuralObject.SetValidValue(value, "ID_Category");
                ReportPropertyChanged("ID_Category");
                OnID_CategoryChanged();
            }
        }
        private global::System.Int32 _ID_Category;
        partial void OnID_CategoryChanging(global::System.Int32 value);
        partial void OnID_CategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_products_tbl_categories", "tbl_categories")]
        public tbl_categories tbl_categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_categories>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_categories>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_categories> tbl_categoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_categories>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_categories>("FlowerAppModel.FK_tbl_products_tbl_categories", "tbl_categories", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_purchases")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_purchases : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_purchases object.
        /// </summary>
        /// <param name="iD_ticket">Initial value of the ID_ticket property.</param>
        /// <param name="code_product">Initial value of the Code_product property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="purchaseID">Initial value of the PurchaseID property.</param>
        public static tbl_purchases Createtbl_purchases(global::System.Int32 iD_ticket, global::System.String code_product, global::System.Int32 quantity, global::System.Int32 purchaseID)
        {
            tbl_purchases tbl_purchases = new tbl_purchases();
            tbl_purchases.ID_ticket = iD_ticket;
            tbl_purchases.Code_product = code_product;
            tbl_purchases.quantity = quantity;
            tbl_purchases.PurchaseID = purchaseID;
            return tbl_purchases;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_ticket
        {
            get
            {
                return _ID_ticket;
            }
            set
            {
                OnID_ticketChanging(value);
                ReportPropertyChanging("ID_ticket");
                _ID_ticket = StructuralObject.SetValidValue(value, "ID_ticket");
                ReportPropertyChanged("ID_ticket");
                OnID_ticketChanged();
            }
        }
        private global::System.Int32 _ID_ticket;
        partial void OnID_ticketChanging(global::System.Int32 value);
        partial void OnID_ticketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code_product
        {
            get
            {
                return _Code_product;
            }
            set
            {
                OnCode_productChanging(value);
                ReportPropertyChanging("Code_product");
                _Code_product = StructuralObject.SetValidValue(value, false, "Code_product");
                ReportPropertyChanged("Code_product");
                OnCode_productChanged();
            }
        }
        private global::System.String _Code_product;
        partial void OnCode_productChanging(global::System.String value);
        partial void OnCode_productChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value, "quantity");
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Int32 _quantity;
        partial void OnquantityChanging(global::System.Int32 value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PurchaseID
        {
            get
            {
                return _PurchaseID;
            }
            set
            {
                if (_PurchaseID != value)
                {
                    OnPurchaseIDChanging(value);
                    ReportPropertyChanging("PurchaseID");
                    _PurchaseID = StructuralObject.SetValidValue(value, "PurchaseID");
                    ReportPropertyChanged("PurchaseID");
                    OnPurchaseIDChanged();
                }
            }
        }
        private global::System.Int32 _PurchaseID;
        partial void OnPurchaseIDChanging(global::System.Int32 value);
        partial void OnPurchaseIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_purchases_tbl_ticket", "tbl_ticket")]
        public tbl_ticket tbl_ticket
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ticket>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_ticket").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ticket>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_ticket").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_ticket> tbl_ticketReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ticket>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_ticket>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_ticket", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_ticket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ticket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ticket object.
        /// </summary>
        /// <param name="ticket">Initial value of the Ticket property.</param>
        /// <param name="datetime">Initial value of the datetime property.</param>
        /// <param name="iD_user">Initial value of the ID_user property.</param>
        /// <param name="iD_ticket">Initial value of the ID_ticket property.</param>
        public static tbl_ticket Createtbl_ticket(global::System.String ticket, global::System.String datetime, global::System.Int32 iD_user, global::System.Int32 iD_ticket)
        {
            tbl_ticket tbl_ticket = new tbl_ticket();
            tbl_ticket.Ticket = ticket;
            tbl_ticket.datetime = datetime;
            tbl_ticket.ID_user = iD_user;
            tbl_ticket.ID_ticket = iD_ticket;
            return tbl_ticket;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ticket
        {
            get
            {
                return _Ticket;
            }
            set
            {
                OnTicketChanging(value);
                ReportPropertyChanging("Ticket");
                _Ticket = StructuralObject.SetValidValue(value, false, "Ticket");
                ReportPropertyChanged("Ticket");
                OnTicketChanged();
            }
        }
        private global::System.String _Ticket;
        partial void OnTicketChanging(global::System.String value);
        partial void OnTicketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value, false, "datetime");
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private global::System.String _datetime;
        partial void OndatetimeChanging(global::System.String value);
        partial void OndatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String deliveryAddress
        {
            get
            {
                return _deliveryAddress;
            }
            set
            {
                OndeliveryAddressChanging(value);
                ReportPropertyChanging("deliveryAddress");
                _deliveryAddress = StructuralObject.SetValidValue(value, true, "deliveryAddress");
                ReportPropertyChanged("deliveryAddress");
                OndeliveryAddressChanged();
            }
        }
        private global::System.String _deliveryAddress;
        partial void OndeliveryAddressChanging(global::System.String value);
        partial void OndeliveryAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_user
        {
            get
            {
                return _ID_user;
            }
            set
            {
                OnID_userChanging(value);
                ReportPropertyChanging("ID_user");
                _ID_user = StructuralObject.SetValidValue(value, "ID_user");
                ReportPropertyChanged("ID_user");
                OnID_userChanged();
            }
        }
        private global::System.Int32 _ID_user;
        partial void OnID_userChanging(global::System.Int32 value);
        partial void OnID_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_ticket
        {
            get
            {
                return _ID_ticket;
            }
            set
            {
                if (_ID_ticket != value)
                {
                    OnID_ticketChanging(value);
                    ReportPropertyChanging("ID_ticket");
                    _ID_ticket = StructuralObject.SetValidValue(value, "ID_ticket");
                    ReportPropertyChanged("ID_ticket");
                    OnID_ticketChanged();
                }
            }
        }
        private global::System.Int32 _ID_ticket;
        partial void OnID_ticketChanging(global::System.Int32 value);
        partial void OnID_ticketChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_purchases_tbl_ticket", "tbl_purchases")]
        public EntityCollection<tbl_purchases> tbl_purchases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_purchases>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_purchases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_purchases>("FlowerAppModel.FK_tbl_purchases_tbl_ticket", "tbl_purchases", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_ticket_tbl_users", "tbl_users")]
        public tbl_users tbl_users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_users> tbl_usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_users>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_users object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="mail">Initial value of the mail property.</param>
        /// <param name="telephone">Initial value of the telephone property.</param>
        /// <param name="iD_user">Initial value of the ID_user property.</param>
        public static tbl_users Createtbl_users(global::System.String username, global::System.String name, global::System.String lastname, global::System.String password, global::System.String address, global::System.String mail, global::System.String telephone, global::System.Int32 iD_user)
        {
            tbl_users tbl_users = new tbl_users();
            tbl_users.username = username;
            tbl_users.name = name;
            tbl_users.lastname = lastname;
            tbl_users.password = password;
            tbl_users.address = address;
            tbl_users.mail = mail;
            tbl_users.telephone = telephone;
            tbl_users.ID_user = iD_user;
            return tbl_users;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false, "lastname");
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, false, "mail");
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, false, "telephone");
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_user
        {
            get
            {
                return _ID_user;
            }
            set
            {
                if (_ID_user != value)
                {
                    OnID_userChanging(value);
                    ReportPropertyChanging("ID_user");
                    _ID_user = StructuralObject.SetValidValue(value, "ID_user");
                    ReportPropertyChanged("ID_user");
                    OnID_userChanged();
                }
            }
        }
        private global::System.Int32 _ID_user;
        partial void OnID_userChanging(global::System.Int32 value);
        partial void OnID_userChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_creditCard_tbl_users", "tbl_creditCard")]
        public EntityCollection<tbl_creditCard> tbl_creditCard
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_creditCard>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_creditCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_creditCard>("FlowerAppModel.FK_tbl_creditCard_tbl_users", "tbl_creditCard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlowerAppModel", "FK_tbl_ticket_tbl_users", "tbl_ticket")]
        public EntityCollection<tbl_ticket> tbl_ticket
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_ticket>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_ticket>("FlowerAppModel.FK_tbl_ticket_tbl_users", "tbl_ticket", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlowerAppModel", Name="tbl_usersRecords")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_usersRecords : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_usersRecords object.
        /// </summary>
        /// <param name="id_record">Initial value of the id_record property.</param>
        public static tbl_usersRecords Createtbl_usersRecords(global::System.Int32 id_record)
        {
            tbl_usersRecords tbl_usersRecords = new tbl_usersRecords();
            tbl_usersRecords.id_record = id_record;
            return tbl_usersRecords;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_record
        {
            get
            {
                return _id_record;
            }
            set
            {
                if (_id_record != value)
                {
                    Onid_recordChanging(value);
                    ReportPropertyChanging("id_record");
                    _id_record = StructuralObject.SetValidValue(value, "id_record");
                    ReportPropertyChanged("id_record");
                    Onid_recordChanged();
                }
            }
        }
        private global::System.Int32 _id_record;
        partial void Onid_recordChanging(global::System.Int32 value);
        partial void Onid_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> record_time
        {
            get
            {
                return _record_time;
            }
            set
            {
                Onrecord_timeChanging(value);
                ReportPropertyChanging("record_time");
                _record_time = StructuralObject.SetValidValue(value, "record_time");
                ReportPropertyChanged("record_time");
                Onrecord_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _record_time;
        partial void Onrecord_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onrecord_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user
        {
            get
            {
                return _user;
            }
            set
            {
                OnuserChanging(value);
                ReportPropertyChanging("user");
                _user = StructuralObject.SetValidValue(value, true, "user");
                ReportPropertyChanged("user");
                OnuserChanged();
            }
        }
        private global::System.String _user;
        partial void OnuserChanging(global::System.String value);
        partial void OnuserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value, true, "class");
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.String _class;
        partial void OnclassChanging(global::System.String value);
        partial void OnclassChanged();

        #endregion

    }

    #endregion

}
