//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFlowerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_users()
        {
            this.tbl_creditCard = new HashSet<tbl_creditCard>();
            this.tbl_ticket = new HashSet<tbl_ticket>();
        }
    
        public string username { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string mail { get; set; }
        public string telephone { get; set; }
        public int ID_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_creditCard> tbl_creditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ticket> tbl_ticket { get; set; }
    }
}
