//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFlowerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ticket()
        {
            this.tbl_purchases = new HashSet<tbl_purchases>();
        }
    
        public string Ticket { get; set; }
        public string datetime { get; set; }
        public string deliveryAddress { get; set; }
        public int ID_user { get; set; }
        public int ID_ticket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purchases> tbl_purchases { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
