//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFlowerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usersRecords
    {
        public int id_record { get; set; }
        public Nullable<System.DateTime> record_time { get; set; }
        public string description { get; set; }
        public string user { get; set; }
        public string @class { get; set; }
    }
}
